services:
  - type: web
    name: nexaerp-api
    env: node
    rootDir: apps/api
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SSL
        value: true
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
